#!/usr/bin/env bash
# Bash script changes the localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
